name: Build For Mac OS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        target: [macos]
        build_type: [release, debug]
        include:
          # Build type to cmake keyword.
          - build_type: release
            cmake_build_type_keyword: Release

          - build_type: debug
            cmake_build_type_keyword: RelWithDebInfo

          - os: macos-latest
            target: macos
            lib_suffix: dylib

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: latest

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Set up CMake for Host tools
        shell: bash
        run: |
          if [ ! -d "${{ github.workspace }}/host-tools-build" ]; then
            mkdir "${{ github.workspace }}/host-tools-build"
          fi
          cd "${{ github.workspace }}/host-tools-build"
          cmake "${{ github.workspace }}/thirdparty/iree" -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/host-tools-build/install" \
            -DHAVE_STD_REGEX=ON -DRUN_HAVE_STD_REGEX=ON \
            -DIREE_ENABLE_WERROR_FLAG=OFF \
            -DIREE_BUILD_COMPILER=OFF

      - name: Build Host tools
        shell: bash
        run: cmake --build ${{ github.workspace }}/host-tools-build --target install

      - name: Set up CMake for MacOS x86_64
        shell: bash
        run: |
          if [ ! -d "${{ github.workspace }}/build_x86_64" ]; then
            mkdir "${{ github.workspace }}/build_x86_64"
          fi
          cd "${{ github.workspace }}/build_x86_64"
          cmake "${{ github.workspace }}" -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type_keyword }} \
            -DIREE_HOST_BIN_DIR="${{ github.workspace }}/host-tools-build/install/bin" \
            -DCMAKE_OSX_ARCHITECTURES="x86_64" \
            -DCMAKE_OSX_SYSROOT=$(xcodebuild -version -sdk macosx Path) \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
            -DIREE_ENABLE_WERROR_FLAG=OFF \
            -DIREE_BUILD_COMPILER=OFF \
            -DIREE_BUILD_SAMPLES=OFF \
            -DIREE_BUILD_TESTS=OFF \
            -DHAVE_STD_REGEX=ON

      - name: Build project x86_64
        shell: bash
        run: cmake --build "${{ github.workspace }}/build_x86_64"

      - name: Set up CMake for MacOS arm64
        shell: bash
        run: |
          if [ ! -d "${{ github.workspace }}/build_arm64" ]; then
            mkdir "${{ github.workspace }}/build_arm64"
          fi
          cd "${{ github.workspace }}/build_arm64"
          cmake "${{ github.workspace }}" -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type_keyword }} \
            -DIREE_HOST_BIN_DIR="${{ github.workspace }}/host-tools-build/install/bin" \
            -DCMAKE_OSX_ARCHITECTURES="arm64" \
            -DCMAKE_OSX_SYSROOT=$(xcodebuild -version -sdk macosx Path) \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
            -DIREE_ENABLE_WERROR_FLAG=OFF \
            -DIREE_BUILD_COMPILER=OFF \
            -DIREE_BUILD_SAMPLES=OFF \
            -DIREE_BUILD_TESTS=OFF \
            -DHAVE_STD_REGEX=ON

      - name: Build project arm64
        shell: bash
        run: cmake --build "${{ github.workspace }}/build_arm64"

      - name: Make Universal lib
        shell: bash
        run: lipo -create -output build/lib/${{ matrix.target }}.${{ matrix.build_type }}.framework/${{ matrix.target }}.${{ matrix.build_type }} build_arm64/lib/*iree-gd*.${{ matrix.lib_suffix }} build_x86_64/lib/*iree-gd*.${{ matrix.lib_suffix }}

      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: iree.gd
          path: "${{ github.workspace }}/build/lib/${{ matrix.target }}.${{ matrix.build_type }}.framework/${{ matrix.target }}.${{ matrix.build_type }}"
          if-no-files-found: error
